sudo: required
language: go

go:
  - 1.6
  - 1.7
  - tip

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y unzip protobuf-compiler

before_script:
  - go generate -v grpcutil/grpc_handler_test.go

install:
  - go get -v github.com/hooklift/assert
  - go get -v golang.org/x/net/xsrftoken
  - go get -v github.com/satori/go.uuid
  - go get -v google.golang.org/grpc
  - go get -v github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway
  - go get -v github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger
  - go get -v github.com/golang/protobuf/protoc-gen-go
