sudo: required
language: go

env:
  - PROTOBUF_VERSION=3.1.0

go:
  - 1.6
  - 1.7
  - tip

before_install:
  - wget https://github.com/google/protobuf/releases/download/v3.1.0/protoc-3.1.0-linux-x86_64.zip 
  - unzip protoc-3.1.0-linux-x86_64.zip
  - export PATH=$PATH:$PWD/protoc-3.1.0-linux-x86_64/bin/protoc
  - protoc --version

install:
  - go get -v github.com/hooklift/assert
  - go get -v golang.org/x/net/xsrftoken
  - go get -v github.com/satori/go.uuid
  - go get -v google.golang.org/grpc
  - go get -v github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway
  - go get -v github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger
  - go get -v github.com/golang/protobuf/protoc-gen-go
