sudo: required
language: go

env:
  - PROTOBUF_VERSION=3.1.0

go:
  - 1.6
  - 1.7
  - tip

before_install:
  - wget https://github.com/google/protobuf/releases/download/v$PROTOBUF_VERSION/protoc-$PROTOBUF_VERSION-linux-x86_64.zip 
  - unzip protoc-$PROTOBUF_VERSION-linux-x86_64.zip
  - mkdir -p $HOME/bin
  - cp bin/protoc $HOME/bin
  - export PATH=$PATH:$HOME/bin
  - protoc --version

before_script:
  - echo $GOPATH
  - export GOPATH=$HOME/gopath
  - go generate -v grpcutil/grpc_handler_test.go

install:
  - go get -v github.com/hooklift/assert
  - go get -v golang.org/x/net/xsrftoken
  - go get -v github.com/satori/go.uuid
  - go get -v google.golang.org/grpc
  - go get -v github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway
  - go get -v github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger
  - go get -v github.com/golang/protobuf/protoc-gen-go
